export enum BlockType {
  air = 0,
  sand = 1,
  tree = 2,
  leaf = 3,
  dirt = 4,
  stone = 5,
  coal = 6,
  wood = 7,
  diamond = 8,
  gold = 9,
  glowstone = 10,
  bedrock = 11,
  glass = 12,
  redstone_lamp = 13,
  grass = 14,
  obsidian = 15,
  water = 16,
  gravel = 17,
  clay = 18,
  snow = 19,
  ice = 20,
  sandstone = 21,
  red_sand = 22,
  cobblestone = 23,
  mossy_cobblestone = 24,
  iron_ore = 25,
  gold_ore = 26,
  diamond_ore = 27,
  coal_ore = 28,
  podzol = 29,
  mycelium = 30,
  terracotta = 31,
  packed_ice = 32,

  // Decoration blocks
  tall_grass = 33,
  fern = 34,
  dead_bush = 35,
  dandelion = 36,
  poppy = 37,
  blue_orchid = 38,
  allium = 39,
  azure_bluet = 40,
  red_tulip = 41,
  orange_tulip = 42,
  white_tulip = 43,
  pink_tulip = 44,
  oxeye_daisy = 45,
  cornflower = 46,
  lily_of_valley = 47,
  brown_mushroom = 48,
  red_mushroom = 49,
  sugar_cane = 50,
  cactus = 51,
  seagrass = 52,
  kelp = 53,

  // Tree variants (for different biome trees)
  birch_log = 54,
  spruce_log = 55,
  jungle_log = 56,
  acacia_log = 57,
  dark_oak_log = 58,
  birch_leaves = 59,
  spruce_leaves = 60,
  jungle_leaves = 61,
  acacia_leaves = 62,
  dark_oak_leaves = 63,

  // Crops and special blocks
  pumpkin = 64,
  jack_o_lantern = 65  // Cave entrance marker (emissive)
}
